### PR TITLE
CMake build system

### PR DESCRIPTION
**Pull request by rajeeja**
First draft. 
Works with conda installed dependencies.
More testing and generalization can be done in future PRs.

### CODE REVIEW

**Comment by rljacob** [comment]
Did you guys write your own FindNetCDF.cmake ?

**Comment by rljacob** [comment]
Is a conda-install of NetCDF or WxWidgets required?

**Comment by rajeeja** [comment]
> Is a conda-install of NetCDF or WxWidgets required?

both

**Comment by rajeeja** [comment]
> Did you guys write your own FindNetCDF.cmake ?

@vijaysm correct me if I'm wrong. Borrowed from MOAB etc.

**Comment by rljacob** [comment]
I meant do you have to do conda installs or could you install them yourself by some other means?

**Comment by vijaysm** [comment]
> > Did you guys write your own FindNetCDF.cmake ?
> 
> @vijaysm correct me if I'm wrong. Borrowed from MOAB etc.

Actually, this is borrowed from VTK and modified. The one from MOAB is more complicated, and requires HDF5 etc. That may still be needed here for more complicated installations I think. Nevertheless, on macbook (spack TPL installs) and Cori, it works out of the box for now. Other systems, may have to play around to see if it works or not.

**Comment by vijaysm** [comment]
> I meant do you have to do conda installs or could you install them yourself by some other means?

The CMake build system relies on the fact that you have already pre-installed NetCDF somewhere. It does not rely on conda, though having a conda target may be much simpler in terms of handling dependencies if all you care about is the final executable.

**Pull request merged**
