### PR TITLE
Force dynamic linking for compiling to work on cheyenne

### PR DESCRIPTION
**Pull request by taobrienlbl**

### CODE REVIEW

**Comment by paullric** [comment]
Oh, got it.  Seems that a lot of systems require -fPIC.

Could you modify build.sh slightly to remove the "bin/“ on line 7?  I’ve changed the install path to the ncvis root directory.

~ Paul

**Comment by taobrienlbl** [comment]
@paullric  - I ended up going back to static linking.  I can get the build to work and code to run successfully when I opt to use conda-installed libraries rather than NCAR's.  You might want to open a ticket with them about this, since it really shouldn't be this tricky to build a netcdf code.

Here's what I did (after doing `conda activate ncvis; module load gnu/12.1.0`
```bash
(ncvis) tobrien@cheyenne4:~/ncvis> module unload ncarenv
(ncvis) tobrien@cheyenne4:~/ncvis> module unload ncarcompilers
(ncvis) tobrien@cheyenne4:~/ncvis> module unload netcdf
```

And here's what I have installed in my conda environment:
```bash
(ncvis) tobrien@cheyenne4:~/ncvis> conda list
# packages in environment at /glade/u/home/tobrien/miniconda3/envs/ncvis:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
adwaita-icon-theme        41.0                 ha770c72_1    conda-forge
alsa-lib                  1.2.6.1              h7f98852_0    conda-forge
at-spi2-atk               2.38.0               h0630a04_3    conda-forge
at-spi2-core              2.40.3               h0630a04_0    conda-forge
atk-1.0                   2.36.0               h3371d22_4    conda-forge
binutils_impl_linux-64    2.38                 h2a08ee3_1
binutils_linux-64         2.38.0               hc2dff05_0
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.18.1               h7f8727e_0
ca-certificates           2022.6.15            ha878542_0    conda-forge
cairo                     1.16.0            ha61ee94_1011    conda-forge
certifi                   2022.6.15       py310hff52083_0    conda-forge
curl                      7.83.1               h2283fc2_0    conda-forge
cxx-compiler              1.0.0                hf484d3e_0    conda-forge
dbus                      1.13.18              hb2f20db_0
epoxy                     1.5.10               h166bdaf_1    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0
font-ttf-inconsolata      2.001                hcb22688_0
font-ttf-source-code-pro  2.030                hd3eb1b0_0
font-ttf-ubuntu           0.83                 h8b1ccd4_0
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-anaconda            1                    h8fa9717_0
fonts-conda-ecosystem     1                    hd3eb1b0_0
freetype                  2.11.0               h70c0345_0
fribidi                   1.0.10               h7b6447c_0
gcc_impl_linux-64         11.2.0               h1234567_1
gcc_linux-64              11.2.0               h5c386dc_0
gdk-pixbuf                2.42.8               h433bba3_0
gettext                   0.21.0               hf68c758_0
glib                      2.72.1               h6239696_0    conda-forge
glib-tools                2.72.1               h6239696_0    conda-forge
graphite2                 1.3.14               h295c915_1
gst-plugins-base          1.20.3               hf6a322e_0    conda-forge
gstreamer                 1.20.3               hd4edc92_0    conda-forge
gtk3                      3.24.34              h13ada96_0    conda-forge
gxx_impl_linux-64         11.2.0               h1234567_1
gxx_linux-64              11.2.0               hc2dff05_0
harfbuzz                  4.4.1                hf9f4e7c_0    conda-forge
hdf4                      4.2.13               h3ca952b_2
hdf5                      1.10.6               h3ffc7dd_1
hicolor-icon-theme        0.17                 h06a4308_2
icu                       70.1                 h27087fc_0    conda-forge
jpeg                      9e                   h7f8727e_0
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libcups                   2.3.3                hf5a7f15_1    conda-forge
libcurl                   7.83.1               h2283fc2_0    conda-forge
libdeflate                1.12                 h166bdaf_0    conda-forge
libedit                   3.1.20210910         h7f8727e_0
libev                     4.33                 h7f8727e_1
libffi                    3.4.2                h295c915_4
libgcc-devel_linux-64     11.2.0               h1234567_1
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            11.2.0               h00389a5_1
libgfortran5              11.2.0               h1234567_1
libglib                   2.72.1               h2d90d5f_0    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h7f8727e_2
libnetcdf                 4.8.1                h42ceab0_1
libnghttp2                1.47.0               he49606f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.5                h27cfd23_1
libopus                   1.3.1                h7b6447c_0
libpng                    1.6.37               hbc83047_0
librsvg                   2.54.4               h19fe530_0
libssh2                   1.10.0               ha35d2d1_2    conda-forge
libstdcxx-devel_linux-64  11.2.0               h1234567_1
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                hc85c160_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h7b6447c_0
libwebp-base              1.2.2                h7f8727e_0
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.14               h22db469_3    conda-forge
libzip                    1.9.2                hc929e4a_0    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
lz4-c                     1.9.3                h295c915_1
ncurses                   6.3                  h5eee18b_3
openssl                   3.0.5                h166bdaf_1    conda-forge
pango                     1.50.8               hbd2fdc8_0    conda-forge
pcre                      8.45                 h295c915_0
pcre2                     10.37                he7ceb23_1
pip                       22.1.2          py310h06a4308_0
pixman                    0.40.0               h7f8727e_1
pthread-stubs             0.3                  h0ce48e5_1
python                    3.10.5          ha86cf86_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1.2                h7f8727e_1
setuptools                61.2.0          py310h06a4308_0
sqlite                    3.38.5               hc218d9a_0
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tk                        8.6.12               h1ccaba5_0
tzdata                    2022a                hda174b7_0
wheel                     0.37.1             pyhd3eb1b0_0
wxwidgets                 3.2.0                h12dd593_1    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxtst              1.2.3             h7f98852_1002    conda-forge
xorg-recordproto          1.14.2            h7f98852_1002    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007
xz                        5.2.5                h7f8727e_1
zlib                      1.2.12               h7f8727e_2
zstd                      1.5.2                ha4553b6_0
```

**Comment by paullric** [comment]
Can confirm this solves the build issue on Cheyenne.  Thanks!

**Comment by paullric** [comment]
Closing pull request since the modifications to .gitignore and build.sh have already been resolved.

**Pull request closed without merging**
